version: '3.9'
services:
  metabase-secrets:
    image: metabase/metabase:latest
    container_name: metabase-secrets
    hostname: metabase-secrets
    volumes:
    - metabase-vol:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 3306
      MB_DB_USER_FILE: /run/secrets/db_user
      MB_DB_PASS_FILE: /run/secrets/db_password
      MB_DB_HOST: mysql-db
    networks:
      - metanet1-secrets
    depends_on:
      - mysql-db
    secrets:
      - db_password
      - db_user
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    hostname: mysql-db
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
        MYSQL_DATABASE: metabase
        MYSQL_USER_FILE: /run/secrets/db_user
        MYSQL_PASSWORD_FILE: /run/secrets/db_password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
        - mysql-vol:/var/lib/mysql
    networks:
      - metanet1-secrets
    secrets:
      - db_password
      - db_user
networks:
  metanet1-secrets:
    driver: bridge
secrets:
   db_password:
     file: db_password.txt
   db_user:
     file: db_user.txt
volumes:
  mysql-vol:
  metabase-vol: